### ISSUE TITLE
AuthAD plugin under PHP8.1, TLS configuration errors on screen

### ISSUE THREAD

**Issue by tqre-mc** [dokuwiki/dokuwiki#3779]
Configured AuthAD with exactly same configurations as the former version, and getting this error.
`Warning: ldap_start_tls(): Unable to start TLS: Operations error in /dokuwiki/lib/plugins/authad/adLDAP/adLDAP.php on line 638`

Authentication works, and openssl s_client -connect tests tell I'm fine certificate-wise... No idea where this error comes from.

**Comment by fiwswe** [comment]
I don't use AuthAD plugin anywhere, but that said:

[ldap_start_tls](https://www.php.net/manual/en/function.ldap-start-tls) is not really documented. But it returns a `bool` which I would expect to signal, whether STARTTLS was successful or not. This return value is not checked though… (a bug?)

So it is possible that you are accessing AD without encryption here. That would be be dangerous from a security point of view. I would try to get a network packet trace to verify this.

The source code for [ldap_start_tls](https://www.php.net/manual/en/function.ldap-start-tls) confirms this: https://github.com/php/php-src/blob/master/ext/ldap/ldap.c#L3578

If the problem is that the certificate is not trusted — a situation that seems to be assumed [here](https://stackoverflow.com/a/5246683) — then you might figure out if you can get it to be trusted or if accepting untrusted certificates is ok for you. If your PHP is running in a chroot environment, access to the system trust anchors may be restricted for example.

`putenv('LDAPTLS_REQCERT=never');` might help to ignore the check of the certificate if that is what you want. Put it e.g. in `inc/preload.php` (see https://www.dokuwiki.org/devel:preload).

HTH
fiwswe

**Comment by hydrian** [comment]
Did you force LDAPv3 in your config? Doku defaults to LDAPv2 which doesn't support SSL/TLS.

**Comment by aarajotte** [comment]
Make sure you have TLS 1.3, not  just 1.2 only in the options. Definitely
no 1.1 and any SSL  deprecated ;  tks keep up the good optel. - AAr

Au plaisir de servir.

Alec Rajotte, b.eng.
CxO

 År  Technologies  AAr inc.
Montréal - Boston - Auckland - København

ITU-T: (+1) 514.778.9027
IANA:  ***@***.***



Le ven. 16 déc. 2022, à 17 h 58, Ben Tyger ***@***.***> a
écrit :

**Comment by tqre-mc** [comment]
These configurations are available for the authldap plugin, but I'm talking about the bundled authad plugin. I guess I should switch to that...

**Comment by splitbrain** [comment]
I'm closing this, since there isn't any info here to go on. I think @fiwswe is right, that it most probably is a certificate problem. You might want to give the pureldap plugin a try, it is a little friendlier with its error messages and configuration for TLS security.

**Comment by tqre-mc** [comment]
Well, this is not a certificate issue, as TLS handshakes go nicely, and authentication succeeds. Also checked the handshakes and packet captures when logging in to be on the safe side. The queries are made to LDAPS ports, and the port doesn't accept unencrypted queries, so if TLS was not working, authentication also would not.

I'll probably switch to the pureldap plugin as instructed.

Here is a error message from dokuwiki logs, if it is any more help. Sorry for late response and resurrecting a completed issue...

```
2023-05-26 05:33:31     /dokuwiki/lib/plugins/authad/adLDAP/adLDAP.php(638)     E_WARNING: ldap_start_tls(): Unable to start TLS: Operations error
  #0 [internal function]: dokuwiki\ErrorHandler::errorHandler()
  #1 /dokuwiki/lib/plugins/authad/adLDAP/adLDAP.php(638): ldap_start_tls()
  #2 /dokuwiki/lib/plugins/authad/adLDAP/adLDAP.php(604): adLDAP->connect()
  #3 /dokuwiki/lib/plugins/authad/auth.php(634): adLDAP->__construct()
  #4 /dokuwiki/lib/plugins/authad/auth.php(203): auth_plugin_authad->initAdLdap()
  #5 /dokuwiki/inc/common.php(1670): auth_plugin_authad->getUserData()
  #6 /dokuwiki/inc/common.php(1621): userlink()
  #7 /dokuwiki/inc/template.php(890): editorinfo()
  #8 /dokuwiki/lib/tpl/dokuwiki/main.php(64): tpl_pageinfo()
  #9 /dokuwiki/inc/actions.php(27): include('...')
  #10 /dokuwiki/doku.php(126): act_dispatch()
  #11 {main}
```

**Comment by splitbrain** [comment]
> The queries are made to LDAPS ports
> ldap_start_tls()

This doesn't add up. When connecting to LDAPS, encryption is established directly (or the connection will fail). When using STARTTLS and unencrypted connection is opened and then upgraded to be encrypted. Did you enable SSL **and** TLS in the config??

**Comment by tqre-mc** [comment]
Only TLS is enabled.

**Comment by tqre-mc** [comment]
And you are right, STARTTLS is what happens in this case. But the connection is encrypted and works despite the error message.

**Comment by splitbrain** [comment]
turn off tls, enable ssl in the config.

**Comment by ted423** [comment]
I use ssl in dokuwiki docker 
`openssl s_client -connect:addomian:636` get `Verify return code: 0 (ok)`in container console
but authad only can work without ssl

**Comment by ted423** [comment]
try tls
```
2025-04-10 07:37:22
E_WARNING: ldap_start_tls(): Unable to start TLS: Connect error
/var/www/html/lib/plugins.core/authad/adLDAP/adLDAP.php(638)
#0 [internal function]: dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/html/lib/plugins.core/authad/adLDAP/adLDAP.php(638): ldap_start_tls()
#2 /var/www/html/lib/plugins.core/authad/adLDAP/adLDAP.php(604): adLDAP->connect()
#3 /var/www/html/lib/plugins.core/authad/auth.php(646): adLDAP->__construct()
#4 /var/www/html/lib/plugins.core/authad/auth.php(209): auth_plugin_authad->initAdLdap()
#5 /var/www/html/inc/common.php(1698): auth_plugin_authad->getUserData()
#6 /var/www/html/inc/common.php(1646): userlink()
#7 /storage/lib/tpl/bootstrap3/Template.php(584): editorinfo()
#8 /storage/lib/tpl/bootstrap3/main.php(157): dokuwiki\template\bootstrap3\Template->getPageInfo()
#9 /var/www/html/inc/actions.php(30): include('...')
#10 /var/www/html/doku.php(131): act_dispatch()
#11 {main}
```

**Comment by splitbrain** [comment]
I am closing this. No new info has been added. @ted423 feel free to open a new issue where you provide your configuration info.

**Comment by ted423** [comment]
I might consider testing it successfully on other services when I have free time before deciding whether to file an issue. For now, I'll stick with using LDAP temporarily.
btw,I tried add ad ca in container with out use `TLS_REQCERT never`
