### ISSUE TITLE
Fulltext search error "TypeError: array_keys(): Argument #1 ($array) must be of type array, null given" with PHP 8.0

### ISSUE THREAD

**Issue by FelHell** [dokuwiki/dokuwiki#3830]
| Software | Version |
| -- | -- |
| DokuWiki | Release 2022-07-31a "Igor" |
| PHP | 8.0.25 |

If I use an "OR" operator in a search query like `Dolor | Amet` and I have no pages on which these words can be found, the search returns this error:

> TypeError: array_keys(): Argument #1 ($array) must be of type array, null given

The error output in the logfile is:

<pre>2022-11-07 21:17:48     /var/www/html/inc/fulltext.php(609)     TypeError: array_keys(): Argument #1 ($array) must be
 of type array, null given
  #16 {main}
  #15 /var/www/html/doku.php(126): act_dispatch()
  #14 /var/www/html/inc/actions.php(27): include('...')
  #13 /var/www/html/lib/tpl/dokuwiki/main.php(59): tpl_content()
  #12 /var/www/html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
  #11 /var/www/html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #10 /var/www/html/inc/Extension/Event.php(133): call_user_func_array()
  #9 [internal function]: tpl_content_core()
  #8 /var/www/html/inc/template.php(100): dokuwiki\Action\Search->tplContent()
  #7 /var/www/html/inc/Action/Search.php(54): dokuwiki\Action\Search->execute()
  #6 /var/www/html/inc/Action/Search.php(70): ft_pageSearch()
  #5 /var/www/html/inc/fulltext.php(45): dokuwiki\Extension\Event::createAndTrigger()
  #4 /var/www/html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #3 /var/www/html/inc/Extension/Event.php(133): call_user_func_array()
  #2 [internal function]: _ft_pageSearch()
  #1 /var/www/html/inc/fulltext.php(133): ft_resultUnite()
  #0 /var/www/html/inc/fulltext.php(610): array_keys()</pre>

In the function `ft_resultUnite($args)`, the `var_dump` output of `$args` is:
<pre>array(2) { [0]=> NULL [1]=> NULL }</pre>

https://github.com/splitbrain/dokuwiki/blob/1e4e47625a7c46816aa6070feafa9e423046e6fc/inc/fulltext.php#L601-L614

This problem occurs since I've updated my DokuWiki installation to PHP 8.0.

**Comment by FelHell** [comment]
This issue has been fixed in commit e08e2789d1747042763bf9977fc0a7c0dba75785. I cannot reproduce it any more.
