### ISSUE TITLE
Error: Call to undefined function dokuwiki\Extension\sexplode()

### ISSUE THREAD

**Issue by dregad** [dokuwiki/dokuwiki#3979]
I got this in the error log today while testing an upgrade from Igor to Jack.

```
2023-05-26 06:50:48	.../wiki/inc/Extension/PluginTrait.php(70)	Error: Call to undefined function dokuwiki\Extension\sexplode()
  #0 .../wiki/inc/Extension/PluginTrait.php(203): dokuwiki\Extension\Plugin->getPluginName()
  #1 .../wiki/inc/Extension/PluginTrait.php(182): dokuwiki\Extension\Plugin->readDefaultSettings()
  #2 .../wiki/inc/Extension/PluginTrait.php(165): dokuwiki\Extension\Plugin->loadConfig()
  #3 .../wiki/lib/plugins/commentsyntax/action.php(15): dokuwiki\Extension\Plugin->getConf('toolbar_button')
  #4 .../wiki/inc/Extension/EventHandler.php(34): action_plugin_commentsyntax->register(Object(dokuwiki\Extension\EventHandler))
  #5 .../wiki/inc/init.php(224): dokuwiki\Extension\EventHandler->__construct()
  #6 .../wiki/lib/exe/manifest.php(7): require_once('.../wiki/...')
  #7 {main}
```

It occurred only once, and I have not been able to reproduce the problem so far.

Dokuwiki 2023-04-04a
PHP 8.2.5

**Comment by splitbrain** [comment]
probably an opcache problem
