### ISSUE TITLE
Error: Call to undefined function phpseclib\Crypt\php_uname()

### ISSUE THREAD

**Issue by SRamezanH** [dokuwiki/dokuwiki#4009]
When I try to login for the first time:
```
2023-07-09 20:38:39	/home/tngogiso/public_html/dokuwiki/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php(517)	Error: Call to undefined function phpseclib\Crypt\php_uname()
  #0 /home/tngogiso/public_html/dokuwiki/inc/auth.php(369): phpseclib\Crypt\Base->__construct()
  #1 /home/tngogiso/public_html/dokuwiki/inc/auth.php(226): auth_encrypt('######!', 'e1208f2b945be38...')
  #2 /home/tngogiso/public_html/dokuwiki/inc/auth.php(174): auth_login('###', '######!', true, false)
  #3 [internal function]: auth_login_wrapper(Array)
  #4 /home/tngogiso/public_html/dokuwiki/inc/Extension/Event.php(133): call_user_func_array('auth_login_wrap...', Array)
  #5 /home/tngogiso/public_html/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('auth_login_wrap...', true)
  #6 /home/tngogiso/public_html/dokuwiki/inc/auth.php(104): dokuwiki\Extension\Event::createAndTrigger('AUTH_LOGIN_CHEC...', Array, 'auth_login_wrap...')
  #7 /home/tngogiso/public_html/dokuwiki/inc/init.php(232): auth_setup()
  #8 /home/tngogiso/public_html/dokuwiki/doku.php(36): require_once('/home/tngogiso/...')
  #9 {main}
```

PHP 8.1

**Comment by mikesteele81** [comment]
> Error: Call to undefined function phpseclib\Crypt\php_uname()

Test that the global "php_uname()"  function is available in your environment. I suspect it is disabled based on this error message.

**Comment by Klap-in** [comment]
It might be that your hosting had disabled this function. If it is disabled, please check with them.
