### ISSUE TITLE
Bootswrapper bug triggers Dokuwiki Bug, apparently.

### ISSUE THREAD

**Issue by Miro-Collas** [dokuwiki/dokuwiki#4029]
PHP 8.1
Dokuwiki Release 2023-04-04a "Jack Jackrum"
Plugin: [Bootswrapper](https://github.com/LotarProject/dokuwiki-plugin-bootswrapper/)

The plugin has problems of its own, such as https://github.com/giterlizzi/dokuwiki-plugin-bootswrapper/issues/143 for example. But until now, I had not seem any of them affect Dokuwiki itself.

```2023-08-14 23:58:47E_WARNING: Undefined array key 1/home/fswiki/public_html/inc/Debug/DebugHelper.php(52)
    #0 /home/fswiki/public_html/inc/Debug/DebugHelper.php(52): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 52)
    #1 /home/fswiki/public_html/inc/infoutils.php(484): dokuwiki\Debug\DebugHelper::dbgDeprecatedFunction('\\dokuwiki\\Exten...', 2)
    #2 /home/fswiki/public_html/inc/deprecated.php(340): dbg_deprecated('\\dokuwiki\\Exten...')
    #3 /home/fswiki/public_html/lib/plugins/bootswrapper/exe/popup.php(56): trigger_event('MEDIAMANAGER_ST...', Array)
    #4 {main}
2023-08-14 23:58:47E_WARNING: Trying to access array offset on value of type null/home/fswiki/public_html/inc/Debug/DebugHelper.php(66)
    #0 /home/fswiki/public_html/inc/Debug/DebugHelper.php(66): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/home/fswiki/pu...', 66)
    #1 /home/fswiki/public_html/inc/infoutils.php(484): dokuwiki\Debug\DebugHelper::dbgDeprecatedFunction('\\dokuwiki\\Exten...', 2)
    #2 /home/fswiki/public_html/inc/deprecated.php(340): dbg_deprecated('\\dokuwiki\\Exten...')
    #3 /home/fswiki/public_html/lib/plugins/bootswrapper/exe/popup.php(56): trigger_event('MEDIAMANAGER_ST...', Array)
    #4 {main} ```

**Comment by sromeroi** [comment]
The same happens with the bootstrap3 template. In my case, it looks like the bootstrap3 template uses deprecated code, and this triggers an error in Dokuwiki DebugHelper itself.

It is clear that "bootstrap3" should not be doing these deprecated calls and those calls should be fixed in the template itself, but what is interesting here is that this exposes a bug in the dokuwiki code.

```
2023-09-29 00:13:44     /var/www/website/public_html/wiki/inc/Debug/DebugHelper.php(52)      E_WARNING: Undefined array key 1
 #0 /var/www/website/public_html/wiki/inc/Debug/DebugHelper.php(52): dokuwiki\ErrorHandler::errorHandler()
 #1 /var/www/website/public_html/wiki/inc/cache.php(15): dokuwiki\Debug\DebugHelper::dbgDeprecatedFunction()
 #2 /var/www/website/public_html/wiki/lib/tpl/bootstrap3/iconify.php(81): cache->__construct()
 #3 {main}
 
2023-09-29 00:13:44     /var/www/website/public_html/wiki/inc/Debug/DebugHelper.php(66)      E_WARNING: Trying to access array offset on value of type null
 #0 /var/www/website/public_html/wiki/inc/Debug/DebugHelper.php(66): dokuwiki\ErrorHandler::errorHandler()
 #1 /var/www/website/public_html/wiki/inc/cache.php(15): dokuwiki\Debug\DebugHelper::dbgDeprecatedFunction()
 #2 /var/www/website/public_html/wiki/lib/tpl/bootstrap3/iconify.php(81): cache->__construct()
 #3 {main}

2023-09-29 00:13:44     /var/www/websitepublic_html/wiki/inc/Debug/DebugHelper.php(89)      E_WARNING: Undefined array key 1
 #0 /var/www/website/public_html/wiki/inc/Debug/DebugHelper.php(89): dokuwiki\ErrorHandler::errorHandler()
 #1 /var/www/website/public_html/wiki/inc/Debug/PropertyDeprecationHelper.php(83): dokuwiki\Debug\DebugHelper::dbgDeprecatedProperty()
 #2 /var/www/website/public_html/wiki/lib/tpl/bootstrap3/iconify.php(82): dokuwiki\Cache\Cache->__set()
 #3 {main}

2023-09-29 00:13:44     /var/www/website/public_html/wiki/inc/Debug/DebugHelper.php(90)      E_WARNING: Trying to access array offset on value of type null
 #0 /var/www/website/public_html/wiki/inc/Debug/DebugHelper.php(90): dokuwiki\ErrorHandler::errorHandler()
 #1 /var/www/website/public_html/wiki/inc/Debug/PropertyDeprecationHelper.php(83): dokuwiki\Debug\DebugHelper::dbgDeprecatedProperty()
 #2 /var/www/website/public_html/wiki/lib/tpl/bootstrap3/iconify.php(82): dokuwiki\Cache\Cache->__set()
 #3 {main}
```
