### ISSUE TITLE
E_WARNING: JPEGMeta failed parsing image metadata - Got 20 instead of 29 bytes at offset 0

### ISSUE THREAD

**Issue by sromeroi** [dokuwiki/dokuwiki#4076]
Dear colleagues,

I recently upgraded Dokuwiki to `2023-04-04a "Jack Jackrum"` and PHP to 8.1, and I noticed the following errors in my `data/logs/error/` folder:

```
2023-10-02 12:19:40     /var/www/website/public_html/wiki/inc/JpegMeta.php(3180)    
E_WARNING: JPEGMeta failed parsing image metadata of
/var/www/website/public_html/wiki/data/media/linux/linux_ubuntu/screenshot.jpg.
Got 20 instead of 29 bytes at offset 0.
  #0 /var/www/website/public_html/wiki/inc/JpegMeta.php(1571): JpegMeta->_getFixedString()
  #1 /var/www/website/public_html/wiki/inc/JpegMeta.php(342): JpegMeta->_parseMarkerXmp()
  #2 /var/www/website/public_html/wiki/inc/JpegMeta.php(151): JpegMeta->getXmpField()
  #3 /var/www/website/public_html/wiki/inc/JpegMeta.php(609): JpegMeta->getField()
  #4 /var/www/website/public_html/wiki/inc/JpegMeta.php(161): JpegMeta->getTitle()
  #5 /var/www/website/public_html/wiki/inc/template.php(1019): JpegMeta->getField()
  #6 /var/www/website/public_html/wiki/lib/tpl/bootstrap3/detail.php(351): tpl_img_getTag()
  #7 /var/www/website/public_html/wiki/lib/exe/detail.php(45): include('...')
  #8 {main}
```

This error appears when the user clicks on an Image and opens the "Information" / "Image Details" page with the image information, and it happens on several images (not just the one in the example above).

I tried to re-save the file in GIMP and also used `convert` to generate a new (resized) version of the image (just in case the headers are not OK) but the error keeps appearing.

The image is correctly displayed and this is just an `E_WARNING` but I'd like to fix it to get rid of the entries in the error log.

Thanks.

**Comment by Klap-in** [comment]
I have not tested yet. For some context, is there an `conf/mediameta.local.php` defined for this wiki? Can you eventually share an example image?

**Comment by sromeroi** [comment]
> I have not tested yet. For some context, is there an `conf/mediameta.local.php` defined for this wiki? Can you eventually share an example image?

Thanks for your quick response.

Sure, this URL triggers the error (and contains an image you can download):

[Example](https://www.sromero.org/wiki/_detail/linux/linux_ubuntu/ub_bas_ubred.jpg?id=linux%3Alinux_ubuntu%3Alive_cd)

There's no  `confi/mediameta.local.php`, only`conf/mediameta.php`.

Please let me know if the sample image is fine, otherwise I'll provide other URLs / images.

Thanks.

**Comment by sromeroi** [comment]
I found that other user reported the same in the Dokuwiki forums:

[https://forum.dokuwiki.org/d/21183-error-logs-about-images](https://forum.dokuwiki.org/d/21183-error-logs-about-images)

```
2023-06-16 13:55:00E_WARNING: JPEGMeta failed parsing image metadata of /var/www/html/usrnm-dokuwiki/data/media/bws.jpg. Got 22 instead of 29 bytes at offset 0./var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(3180)
#0 /var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(1571): JpegMeta->getFixedString('Exif\x00\x00II*\x00\x08\x00\x00\x00\x00...', 0, 29)
#1 /var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(342): JpegMeta->parseMarkerXmp()
#2 /var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(151): JpegMeta->getXmpField('dc:title')
#3 /var/www/html/usrnm-dokuwiki/inc/Ui/Media/DisplayRow.php(72): JpegMeta->getField(Array)
#4 /var/www/html/usrnm-dokuwiki/inc/Ui/Media/DisplayRow.php(51): dokuwiki\Ui\Media\DisplayRow->showDetails()
#5 /var/www/html/usrnm-dokuwiki/inc/media.php(721): dokuwiki\Ui\Media\DisplayRow->show()
#6 /var/www/html/usrnm-dokuwiki/inc/template.php(1368): media_filelist('', 16, NULL, false, 'natural')
#7 /var/www/html/usrnm-dokuwiki/lib/tpl/dokuwiki/mediamanager.php(39): tpl_mediaContent()
#8 /var/www/html/usrnm-dokuwiki/lib/exe/mediamanager.php(128): include('/var/www/html/r...')
#9 {main}

2023-06-16 13:55:01E_WARNING: JPEGMeta failed parsing image metadata of /var/www/html/usrnm-dokuwiki/data/media/g8ic_construct.jpg. Got 26 instead of 29 bytes at offset 0./var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(3180)
#0 /var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(1571): JpegMeta->getFixedString('Exif\x00\x00II*\x00\x08\x00\x00\x00\x00...', 0, 29)
#1 /var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(342): JpegMeta->parseMarkerXmp()
#2 /var/www/html/usrnm-dokuwiki/inc/JpegMeta.php(151): JpegMeta->getXmpField('dc:subject')
#3 /var/www/html/usrnm-dokuwiki/inc/Ui/Media/DisplayRow.php(80): JpegMeta->getField(Array)
#4 /var/www/html/usrnm-dokuwiki/inc/Ui/Media/DisplayRow.php(51): dokuwiki\Ui\Media\DisplayRow->showDetails()
#5 /var/www/html/usrnm-dokuwiki/inc/media.php(721): dokuwiki\Ui\Media\DisplayRow->show()
#6 /var/www/html/usrnm-dokuwiki/inc/template.php(1368): media_filelist('', 16, NULL, false, 'natural')
#7 /var/www/html/usrnm-dokuwiki/lib/tpl/dokuwiki/mediamanager.php(39): tpl_mediaContent()
#8 /var/www/html/usrnm-dokuwiki/lib/exe/mediamanager.php(128): include('/var/www/html/r...')
#9 {main}
```

Maybe is just a common scenario (wrong headers in JPG files depending on the software that generated them) that now are visible in the logs due to the upgrade to PHP 8.1.

**Comment by jsbham** [comment]
I have the same issue - many images, probably hundreds of these messages, over time.
Release 2023-04-04a "Jack Jackrum"
php v 8.1
server: Apache
Host: Fastcomet
OS: Cloud Linux
Gallery plugin: 2023-09-18 (I see a new version is available)
Reproduce: Just 1 example of many - load page https://na0tc.org/doku.php?id=tf_2018_photos (image 9, for example)
```
2023-11-06 05:57:46E_WARNING: JPEGMeta failed parsing image metadata of /home/natcorg/public_html/data/media/photo/12_anniv/12ann_03.jpg. Got 26 instead of 29 bytes at offset 0./home/natcorg/public_html/inc/JpegMeta.php(3180)
    #0 /home/natcorg/public_html/inc/JpegMeta.php(1571): JpegMeta->_getFixedString()
    #1 /home/natcorg/public_html/inc/JpegMeta.php(1115): JpegMeta->_parseMarkerXmp()
    #2 /home/natcorg/public_html/inc/JpegMeta.php(634): JpegMeta->_parseAll()
    #3 /home/natcorg/public_html/inc/JpegMeta.php(242): JpegMeta->getDates()
    #4 /home/natcorg/public_html/inc/JpegMeta.php(155): JpegMeta->getDateField()
    #5 /home/natcorg/public_html/inc/media.php(1157): JpegMeta->getField()
    #6 /home/natcorg/public_html/inc/media.php(1186): media_getTag()
    #7 /home/natcorg/public_html/inc/media.php(1207): media_file_tags()
    #8 /home/natcorg/public_html/inc/media.php(962): media_details()
    #9 /home/natcorg/public_html/inc/template.php(1486): media_tab_view()
    #10 /home/natcorg/public_html/inc/template.php(1789): tpl_mediaFileDetails()
    #11 /home/natcorg/public_html/inc/Action/Media.php(21): tpl_media()
    #12 /home/natcorg/public_html/inc/template.php(100): dokuwiki\Action\Media->tplContent()
    #13 [internal function]: tpl_content_core()
    #14 /home/natcorg/public_html/inc/Extension/Event.php(133): call_user_func_array()
    #15 /home/natcorg/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #16 /home/natcorg/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #17 /home/natcorg/public_html/lib/tpl/na0tc/main.php(59): tpl_content()
    #18 /home/natcorg/public_html/inc/actions.php(27): include('/home/natcorg/p...')
    #19 /home/natcorg/public_html/doku.php(126): act_dispatch()
```
I have all these images stored locally, and I can open them in Gimp without errors, look at image info and see nothing obvious. Here's an example of image metadata, but I don't if that's the type JPEGmeta is complaining about.
```
$file 630M_transmitter_KD0VBR_09.jpg
630M_transmitter_KD0VBR_09.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 180x180, segment length 16, comment: "630M Transmitter by KD0VBR- Tom", progressive, precision 8, 1392x824, components 3
```
When I look at one of the images named, in the Media Manager, the info column on the right shows:

```
Title:
    630M transmitter KD0VBR
Date:
    2018/11/11 18:17
Filename:
    630m_transmitter_kd0vbr_09.jpg
Caption:
    630M transmitter KD0VBR
Format:
    JPEG
Size:
    526KB
Width:
    1392
Height:
    824

References for:
    Nothing was found.
```
If needed, I can duplicate this DokuWiki install here on my local Ubuntu system, and run any suggested debugging methods.

**Comment by jsbham** [comment]
Here is the mediameta.php file from my installation:
```
$ cat mediameta.php 
<?php
/**
 * This configures which metadata will be editable through
 * the media manager. Each field of the array is an array with the
 * following contents:
 *   fieldname - Where data will be saved (EXIF or IPTC field)
 *   label     - key to lookup in the $lang var, if not found printed as is
 *   htmltype  - 'text', 'textarea' or 'date'
 *   lookups   - array additional fields to look up the data (EXIF or IPTC fields)
 *
 * The fields are not ordered continuously to make inserting additional items
 * in between simpler.
 *
 * This is a PHP snippet, so PHP syntax applies.
 *
 * Note: $fields is not a global variable and will not be available to any
 *       other functions or templates later
 *
 * You may extend or overwrite this variable in an optional
 * conf/mediameta.local.php file
 *
 * For a list of available EXIF/IPTC fields refer to
 * http://www.dokuwiki.org/devel:templates:detail.php
 */


$fields = array(
    10 => array('Iptc.Headline',
                'img_title',
                'text'),

    20 => array('',
                'img_date',
                'date',
                array('Date.EarliestTime')),

    30 => array('',
                'img_fname',
                'text',
                array('File.Name')),

    40 => array('Iptc.Caption',
                'img_caption',
                'textarea',
                array('Exif.UserComment',
                      'Exif.TIFFImageDescription',
                      'Exif.TIFFUserComment')),

    50 => array('Iptc.Byline',
                'img_artist',
                'text',
                array('Exif.TIFFArtist',
                      'Exif.Artist',
                      'Iptc.Credit')),

    60 => array('Iptc.CopyrightNotice',
                'img_copyr',
                'text',
                array('Exif.TIFFCopyright',
                      'Exif.Copyright')),

    70 => array('',
                'img_format',
                'text',
                array('File.Format')),

    80 => array('',
                'img_fsize',
                'text',
                array('File.NiceSize')),

    90 => array('',
                'img_width',
                'text',
                array('File.Width')),

    100 => array('',
                'img_height',
                'text',
                array('File.Height')),

    110 => array('',
                'img_camera',
                'text',
                array('Simple.Camera')),

    120 => array('Iptc.Keywords',
                'img_keywords',
                'text',
                array('Exif.Category')),
);
```

**Comment by splitbrain** [comment]
Please see #1970, JPEGMeta is unmaintained 3rd party code. I lack the understanding of the EXIF/IPTC internals to fix these warnings. If someone wants to dig into this, they are more than welcome. I think it could make an excellent little open source project to modernize and maintain this little class if you're willing to dig into the specifications. Otherwise we have to find an replacement. Until then you will have to deal with the warning.

**Comment by rocrail** [comment]
The same I see with the latest Dokuwiki version.
And with the Log Plugin, which seems to be standard installed, it degrees performance dramatically.
I removed the Log Plugin and now the Wiki is usable again.

**Comment by rocrail** [comment]
Yes, I know, but if a tool can't do its job its kind of worthless.
All parsed JPEG it does not understand, so it has no function and disturbs the rest.

**Comment by sromeroi** [comment]
> Yes, I know, but if a tool can't do its job its kind of worthless.
> All parsed JPEG it does not understand, so it has no function and disturbs the rest.

I think the JPEG files are parsed (and the code works); it just throws the E_WARNING for informational purposes.

**Comment by fiwswe** [comment]
I think the issue is with these lines:
https://github.com/dokuwiki/dokuwiki/blob/133e2f6d07a7b695a4b6bde21f477409f3c32e48/inc/JpegMeta.php#L1573-L1579
There seems to be a different signature than `"http://ns.adobe.com/xap/1.0/\0"` in the XMP data, one that is apparently only 20 bytes long.

Maybe the assumption that this exact 29 byte signature must be present is wrong? May whatever software created the XMP metadata is newer/different and uses a different signature?

An example image file would be nice to verify this.

I have not verified what the XMP spec says, but if someone wants to explore:
https://github.com/adobe/XMP-Toolkit-SDK/tree/main/docs

**Comment by rocrail** [comment]
Is there a fix or work-around for this error?
The Log is full of those errors.

The installed DokuWiki is 2024-02-06b "Kaos" with PHP 8.4

**Comment by rocrail** [comment]
I did comment it out:

```
        try {
            $data = null;
            $count = count($this->_markers);
            for ($i = 0; $i < $count; $i++) {
                if ($this->_markers[$i]['marker'] == 0xE1) {
                    /*
                    $signature = $this->_getFixedString($this->_markers[$i]['data'], 0, 29);
                    if ($signature == "http://ns.adobe.com/xap/1.0/\0") {
                        $data = substr($this->_markers[$i]['data'], 29);
                        break;
                    }
                    */
                }
            }

```
