### ISSUE TITLE
TypeError: implode(): Argument #2 ($array) must be of type ?array, string given

### ISSUE THREAD

**Issue by seadra** [dokuwiki/dokuwiki#4087]
On Debian 12 with PHP 8.2, getting the following error

```
TypeError: implode(): Argument #2 ($array) must be of type ?array, string given

An unforeseen error has occured. This is most likely a bug somewhere.

More info has been written to the DokuWiki error log.

```

debug log says

```
/usr/share/php/simplepie/library/SimplePie/Parse/Date.php(544)  TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
  #0 /usr/share/php/simplepie/library/SimplePie/Parse/Date.php(544): implode()
  #1 /usr/share/php/simplepie/library/SimplePie/Parse/Date.php(577): SimplePie_Parse_Date->__construct()
  #2 /usr/share/php/simplepie/library/SimplePie/Registry.php(222): SimplePie_Parse_Date::get()
  #3 /usr/share/php/simplepie/library/SimplePie/Item.php(772): SimplePie_Registry->call()
  #4 /usr/share/php/simplepie/library/SimplePie.php(2890): SimplePie_Item->get_date()
  #5 /usr/share/php/simplepie/library/SimplePie.php(2777): SimplePie->get_items()
  #6 /usr/share/dokuwiki/inc/parser/xhtml.php(1339): SimplePie->get_item_quantity()
  #7 /usr/share/dokuwiki/inc/parserutils.php(682): Doku_Renderer_xhtml->rss()
  #8 /usr/share/dokuwiki/inc/parserutils.php(149): p_render()
  #9 /usr/share/dokuwiki/inc/parserutils.php(89): p_cached_output()
  #10 /usr/share/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml()
  #11 /usr/share/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
  #12 /usr/share/dokuwiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
  #13 [internal function]: tpl_content_core()
  #14 /usr/share/dokuwiki/inc/Extension/Event.php(133): call_user_func_array()
  #15 /usr/share/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #16 /usr/share/dokuwiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
  #17 /var/lib/dokuwiki/lib/tpl/r7throot2/main.php(96): tpl_content()
  #18 /usr/share/dokuwiki/inc/actions.php(27): include('...')
  #19 /usr/share/dokuwiki/doku.php(126): act_dispatch()
  #20 {main}
```

**Comment by seadra** [comment]
Seems like https://github.com/simplepie/simplepie/issues/686 ?

**Comment by Klap-in** [comment]
In DokuWiki we have version 1.8.0 of simplepie included, if I see it right that version is also included in last release (Jack Jackrum).
Which version of DokuWiki do you use? My impression is that this code was only in older versions of DokuWiki?

**Comment by seadra** [comment]
Using the dokuwiki from the package manager
https://packages.debian.org/bookworm/dokuwiki version is 20220731.a-2

**Comment by Klap-in** [comment]
The latest version of DokuWiki has the most improvements for newer php versions. With older versions you can expect troubles.

Good to see Debian includes a bit more recent version of DokuWiki, but unfortunately not yet the latest. Therefore, we recommend to not use the version from the package manager of Debian, but direct download it from our download page such that you are up to date. If using the package manager version, you should use a php version that matches that version, surely not the latest php version.

**Comment by Klap-in** [comment]
I think we can close this issue, as it is fixed in our last release. So no work left for us.

**Comment by Farom** [comment]
For all Debianusers who finds this: libphp-simplepie from bookworm-backports (1.5.8+dfsg-1~bpo12+1) solves this issue.
