### ISSUE TITLE
Upgrade from Jack Jackrun to Kaos failed on last step

### ISSUE THREAD

**Issue by zounp** [dokuwiki/dokuwiki#4227]
### The problem

The upgrade of Dokuwiki failed but Dokuwiki seems to be upgraded.
An other issue arose: The Delete languages plugin gave an error. See below.

### Version of DokuWiki

2024-02-06a "Kaos"

### PHP Version

PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)

### Webserver and version of webserver

lighttpd/1.4.69 (ssl) on Debian 12.4 Bookworm

### Browser and version of browser, operating system running browser

Firefox 123.0, Debian 12.4 Bookworm

### Additional environment information

Plugins: Backup tool, Delete Language, Wiki Upgrade

### Relevant logs and/or error messages

When Upgrading to Kaos I got, in the last step, something like "Something went wrong, do not continue". I have upgraded Dokuwiki before on this machine without issues. Also I upgraded other instances of Dokuwiki running on PHP 7.something on other machines without issues today.

There were red crosses with the files doku.php, feed.php, index.php, install.php.
I restarted the upgrade and got that Dokuwiki was upgraded, so nothing to do.

I compared the doku.php, feed.php, index.php, files and they were identical to the files from an other Dokuwiki instance I upgraded today. install.php was not present anymore in the successfully upgraded Dokuwiki instance. It is present in the unsuccessful instance. 

I ran install.php and got errors:

```text
./install.php: line 1: ?php: No such file or directory                                         
./install.php: line 3: syntax error near unexpected token `<'                                  
./install.php: line 3: `/*><div style="width:60%; margin: auto; background-color: #fcc;'
```

Then I ran the Delete language plugin and got this error:

```text
TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given
	An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the langdelete plugin.
	More info has been written to the DokuWiki error log.
```

In the Dokuwiki log I found a lot of entries:

```text
2024-02-28 15:46:58     /var/www/html/dokuwiki/lib/plugins/langdelete/admin.php(415)    E_WARNING: Undefined array key "af"
  #0 /var/www/html/dokuwiki/lib/plugins/langdelete/admin.php(415): dokuwiki\ErrorHandler::errorHandler()
  #1 /var/www/html/dokuwiki/lib/plugins/langdelete/admin.php(77): admin_plugin_langdelete->lang_unique()
  #2 /var/www/html/dokuwiki/inc/Action/Admin.php(35): admin_plugin_langdelete->handle()
  #3 /var/www/html/dokuwiki/inc/ActionRouter.php(86): dokuwiki\Action\Admin->preProcess()
  #4 /var/www/html/dokuwiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
  #5 /var/www/html/dokuwiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #6 /var/www/html/dokuwiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
  #7 /var/www/html/dokuwiki/doku.php(131): act_dispatch()
  #8 {main}
and this for every language it seems.
```

**Comment by splitbrain** [comment]
no clear error descriptions. errors possibly related to different plugins (should be reported separately to involved plugins)
