### ISSUE TITLE
Medai Manager error with Release 2024-02-06a "Kaos" & Bootstrap3

### ISSUE THREAD

**Issue by Calistenie** [dokuwiki/dokuwiki#4251]
### The problem

After installation Release 2024-02-06a "Kaos" there is a probleme when you are in edit mode of a page and you click to add an image to access to the media manager.
the pop-up window to add à media let appears an error message : 

Warning: Undefined array key "id" in C:\wamp64\www\dokuwikidavid\inc\Menu\Item\Edit.php on line 42

### Version of DokuWiki

2024-02-06a "Kaos"

### PHP Version

8.3

### Webserver and version of webserver

Apache 2.4 on Windows

### Browser and version of browser, operating system running browser

Firefox 124.0.1 on Windows

### Relevant logs and/or error messages

```text
Warning: Undefined array key "id" in C:\wamp64\www\dokuwikidavid\inc\Menu\Item\Edit.php on line 42
Call Stack
#	Time	Memory	Function	Location
1	0.0003	366176	{main}( )	...\mediamanager.php:0
2	0.1159	482096	include( 'C:\wamp64\www\dokuwikidavid\lib\tpl\bootstrap3\mediamanager.php )	...\mediamanager.php:130
3	0.1160	482448	require_once( 'C:\wamp64\www\dokuwikidavid\lib\tpl\bootstrap3\tpl\global.php )	...\mediamanager.php:13
4	0.1280	486944	dokuwiki\template\bootstrap3\Template::getInstance( )	...\global.php:32
5	0.1280	487512	dokuwiki\template\bootstrap3\Template->__construct( )	...\Template.php:121
6	0.1282	488032	dokuwiki\template\bootstrap3\Template->initToolsMenu( )	...\Template.php:36
7	0.1484	506952	dokuwiki\Menu\AbstractMenu->getItems( )	...\Template.php:2329
8	0.1484	507576	dokuwiki\Extension\Event::createAndTrigger( $name = 'MENU_ITEMS_ASSEMBLY', $data = ['view' => 'page', 'items' => []], $action = [0 => class dokuwiki\template\bootstrap3\Menu\PageMenu { protected $types = [...]; protected $context = 1; protected $view = 'page' }, 1 => 'loadItems'], $canPreventDefault = ??? )	...\AbstractMenu.php:45
9	0.1484	507736	dokuwiki\Extension\Event->trigger( $action = [0 => class dokuwiki\template\bootstrap3\Menu\PageMenu { protected $types = [...]; protected $context = 1; protected $view = 'page' }, 1 => 'loadItems'], $enablePrevent = TRUE )	...\Event.php:200
10	0.1484	507952	call_user_func_array:{C:\wamp64\www\dokuwikidavid\inc\Extension\Event.php:134}( $callback = [0 => class dokuwiki\template\bootstrap3\Menu\PageMenu { protected $types = [...]; protected $context = 1; protected $view = 'page' }, 1 => 'loadItems'], $args = [0 => ['view' => 'page', 'items' => [...]]] )	...\Event.php:134
11	0.1484	508024	dokuwiki\Menu\AbstractMenu->loadItems( $data = ['view' => 'page', 'items' => []] )	...\Event.php:134
12	0.1494	508480	dokuwiki\Menu\Item\Edit->__construct( )	...\AbstractMenu.php:61
Sélection de fichiers

edit.php :
<?php

namespace dokuwiki\Menu\Item;

/**
 * Class Edit
 *
 * Most complex item. Shows the edit button but mutates to show, draft and create based on
 * current state.
 */
class Edit extends AbstractItem
{
    /** @inheritdoc */
    public function __construct()
    {
        global $ACT;
        global $INFO;
        global $REV;

        parent::__construct();

        if ($ACT === 'show') {
            $this->method = 'post';
            if ($INFO['writable']) {
                $this->accesskey = 'e';
                if (!empty($INFO['draft'])) {
                    $this->type = 'draft';
                    $this->params['do'] = 'draft';
                } else {
                    $this->params['rev'] = $REV;
                    if (!$INFO['exists']) {
                        $this->type = 'create';
                    }
                }
            } else {
                if (!actionOK("source")) throw new \RuntimeException("action disabled: source");
                $params['rev'] = $REV;
                $this->type = 'source';
                $this->accesskey = 'v';
            }
        } else {
            if (auth_quickaclcheck($INFO['id']) < AUTH_READ) throw new \RuntimeException("no permission to read");
            $this->params = ['do' => ''];
            $this->type = 'show';
            $this->accesskey = 'v';
        }

        $this->setIcon();
    }

    /**
     * change the icon according to what type the edit button has
     */
    protected function setIcon()
    {
        $icons = [
            'edit' => '01-edit_pencil.svg',
            'create' => '02-create_pencil.svg',
            'draft' => '03-draft_android-studio.svg',
            'show' => '04-show_file-document.svg',
            'source' => '05-source_file-xml.svg'
        ];
        if (isset($icons[$this->type])) {
            $this->svg = DOKU_INC . 'lib/images/menu/' . $icons[$this->type];
        }
    }
}
```

**Comment by tstoll1024** [comment]
I have the same problem with
2024-02-06b "Kaos" & Bootstrap3
PHP 8.2.11
on Edge Version 129.0.2792.65 (Firefox the same problem)
and the additional error message

"dokuwiki\lib\plugins\dw2pdf\action.php(1093)	E_WARNING: Undefined array key "exists""

**Comment by elivoncoder** [comment]
`(mod_fastcgi.c.477) FastCGI-stderr:PHP Warning:  Undefined array key "id" in /var/www/html/inc/Menu/Item/Edit.php on line 42`

i think its the same issue?  this is from my lighttpd error.log. 

librarian, php8.4, bootstrap3 template, and bootstrap-wrapper.

heres the accompanying dokuwki errorlog

`E_WARNING: Undefined array key "id"/var/www/html/inc/Menu/Item/Edit.php(42)
    #0 /var/www/html/inc/Menu/Item/Edit.php(42): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/html/inc/Menu/AbstractMenu.php(67): dokuwiki\Menu\Item\Edit->__construct()
    #2 [internal function]: dokuwiki\Menu\AbstractMenu->loadItems()
    #3 /var/www/html/inc/Extension/Event.php(134): call_user_func_array()
    #4 /var/www/html/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
    #5 /var/www/html/inc/Menu/AbstractMenu.php(45): dokuwiki\Extension\Event::createAndTrigger()
    #6 /var/www/html/lib/tpl/bootstrap3/Template.php(2343): dokuwiki\Menu\AbstractMenu->getItems()
    #7 /var/www/html/lib/tpl/bootstrap3/Template.php(36): dokuwiki\template\bootstrap3\Template->initToolsMenu()
    #8 /var/www/html/lib/tpl/bootstrap3/Template.php(121): dokuwiki\template\bootstrap3\Template->__construct()
    #9 /var/www/html/lib/tpl/bootstrap3/tpl/global.php(32): dokuwiki\template\bootstrap3\Template::getInstance()
    #10 /var/www/html/lib/tpl/bootstrap3/mediamanager.php(13): require_once('...')
    #11 /var/www/html/lib/exe/mediamanager.php(130): include('...')
    #12 {main}`

**Comment by hiSandog** [comment]
The Bootstrap3 media-manager warning looks like a compatibility regression around menu item context. Even if the core code expects an `id`, the popup path should guard missing context and avoid emitting PHP warnings into the media dialog. A regression test with the Bootstrap3 plugin opening the media manager from edit mode would cover the reported path.

**Comment by fiwswe** [comment]
Does this problem also happen with the default template? If not, the issue should probably be filed against the [Bootstrap3 Template](https://github.com/giterlizzi/dokuwiki-template-bootstrap3/issues).
