### ISSUE TITLE
Warnings being thrown on invalid table

### ISSUE THREAD

**Issue by eduardomozart** [dokuwiki/dokuwiki#4316]
### The problem

Hello,
I know the markdown below contains an invalid table (it missing a ``|`` between ``app2-ap.central.arubanetworks.com app1-ap.central.arubanetworks.com``):

```===== Regras de Firewall =====

A maior parte da comunicação entre os dispositivos no local remoto e o servidor Aruba Central na nuvem é realizada por meio de HTTPS (TCP 443). Para permitir que os dispositivos se comuniquem por meio de um firewall de rede, certifique-se de que os seguintes nomes de domínio e portas estejam abertos. [(:harvard:Aruba-Central-User-Guide>>page:94)]

<table tab_label>
<caption>Nomes de domínio para Aruba Central Portal Access. \\ FONTE: [(:harvard:Aruba-Central-User-Guide>>direct:yes;page:97)].</caption>
^Região       ^Nome de domínio                         ^Protocolo     ^
|US-1         |app1.hybrid.central.arubanetworks.com   |Porta TCP 443 |
|US-2         |hc-prod2.central.arubanetworks.com      | ::: |
|US West      |uswest4-hc.central.arubanetworks.com    | ::: |
|EU-1         |central-eu-hc.central.arubanetworks.com | ::: |
|EU Central   |eucentral3-hc.central.arubanetworks.com | ::: |
|CA Central   |ca-hc.central.arubanetworks.com         | ::: |
|AP South     |apac-hc.central.arubanetworks.com       | ::: |
|AP Northeast |apaceast-hc.central.arubanetworks.com   | ::: |
|AP-SouthEast |apacsouth-hc.central.arubanetworks.com  | ::: |
|UAE North    |uaenorth1.central.arubanetworks.com     | ::: |
</table>

<table tab_label>
<caption>Nomes de domínio para comunicação de dispositivos com o Aruba Central. \\ FONTE: [(:harvard:Aruba-Central-User-Guide>>direct:yes;pages:98-99)].</caption>
^Região  ^URL do Aruba Central ^URL para conectividade de dispositivo    ^Protocolo              ^
|US-1    |app.central.arubanetworks.com            |app1.central.arubanetworks.com |Porta TCP 443 |
|US-2    |appprod2.central.arubanetworks.com       |deviceprod2.central.arubanetworks.com | ::: |
|US West |device-uswest4.central.arubanetworks.com |device-uswest4.central.arubanetworks.com | ::: |
|EU Central |appeucentral3.central.arubanetworks.com |deviceeucentral3.central.arubanetworks.com | ::: |
|CA Central |app-ca.central.arubanetworks.com |device-ca.central.arubanetworks.com | ::: |
|CN North |app.central.arubanetworks.com |device.central.arubanetworks.com | ::: |
|AP South |app2-ap.central.arubanetworks.com app1-ap.central.arubanetworks.com | ::: |
|AP Northeast |appapaceast.central.arubanetworks.com |deviceapaceast.central.arubanetworks.com | ::: |
|AP SouthEast |appapacsouth.central.arubanetworks.com |deviceapacsouth.central.arubanetworks.com | ::: |
|UAE North |appuaenorth1.central.arubanetworks.com |device-uaenorth1-d2.central.arubanetworks.com | ::: |
</table>

<table tab_label>
<caption>Nomes de domínio para comunicação de dispositivos com Aruba Activate. \\ FONTE: [(:harvard:Aruba-Central-User-Guide>>direct:yes;page:100)].</caption>
^Nome de domínio              ^Protocolo     ^
|device.arubanetworks.com     |Porta TCP 443 |
|devices-v2.arubanetworks.com | :::          |
|est.arubanetworks.com        | :::          |
</table>

<table tab_label>
<caption>Domínios de Servidor de Convidados em Nuvem para Serviço de Acesso de Convidados. \\ FONTE: [(:harvard:Aruba-Central-User-Guide>>direct:yes;page:100-101)].</caption>
^Região  ^Nome de Domínio ^Protocolo ^
|US-1    |naw2.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| :::    |naw2-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|US-2 |nae1.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| :::    |nae1-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|US West |uswest4.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| :::    |uswest4-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|EU-1    |euw1.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| :::    |euw1-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|EU Central |euw1.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| ::: |euw1-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|CA Central |ca.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| ::: |ca-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|AP South |ap1.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| ::: |ap1-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|AP NorthEast |apaceast.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| ::: |apaceast-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|AP SouthEast |apacsouth.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| ::: |apacsouth-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
|UAE North |asw1.cloudguest.central.arubanetworks.com |<WRAP>
  * Porta TCP 2083
  * Porta TCP 443
</WRAP>  |
| ::: |asw1-elb.cloudguest.central.arubanetworks.com |Porta TCP 443 |
</table>

<table tab_label>
<caption>Nomes de domínio para OpenFlow. \\ FONTE: [(:harvard:Aruba-Central-User-Guide>>direct:yes;page:101)].</caption>
^Região  ^Nome de domínio                       ^
|US-1 |https://app2-ofc.central.arubanetworks.com|
|US-2 |https://ofc-prod2.central.arubanetworks.com|
|US West |https://ofc-uswest4.central.arubanetworks.com|
|EU-1 |https://app2-eu-ofc.central.arubanetworks.com|
|EU Central |https://ofc-eucentral3.central.arubanetworks.com|
|CA Central |https://ofc-ca.central.arubanetworks.com|
|CN North |https://ofc.central.arubanetworks.com.cn|
|AP South |https://app2-ap-ofc.central.arubanetworks.com|
|AP NorthEast |https://ofc-apaceast.central.arubanetworks.com|
|AP SouthEast |https://ofc-apacsouth.central.arubanetworks.com|
|UAE North |https://ofc-uaenorth1.central.arubanetworks.com|
</table>

<table tab_label>
<caption>Nomes de domínio para RCS. \\ FONTE: [(:harvard:Aruba-Central-User-Guide>>direct:yes;pages:101-102)].</caption>
^Região  ^Nome de domínio                                   ^Protocolo     ^
|US-1    |rcs-ng-prod.central.arubanetworks.com             |Porta SSH 443 |
| :::    |rcs-ng-xp-prod.central.arubanetworks.com          | :::          |
|US-2    |rcs-ng-central-prod2.central.arubanetworks.com    |Porta SSH 443 |
| :::    |rcs-ng-xp-central-prod2.central.arubanetworks.com | :::          |
|US West |rcs-ng-uswest4.central.arubanetworks.com          |Porta SSH 443 |
| :::    |rcs-ng-xp-uswest4.central.arubanetworks.com       | :::          |
|EU-1    |rcs-ng-eu.central.arubanetworks.com               |Porta SSH 443 |
| :::    |rcs-ng-xp-eu.central.arubanetworks.com            | :::          |
|EU Central |rcs-ng-eucentral3.central.arubanetworks.com    |Porta SSH 443 |
| :::       |rcs-ng-xp-eucentral3.central.arubanetworks.com | :::          |
|CA Central |rcs-ng-starman.central.arubanetworks.com       |Porta SSH 443 |
| :::       |rcs-ng-xp-starman.central.arubanetworks.com    | :::          |
|CN North   |rcs-ng-china-prod.central.arubanetworks.com.cn |Porta SSH 443 |
|AP South   |rcs-ng-apac.central.arubanetworks.com          |Porta SSH 443 |
| :::       |rcs-ng-xp-apac.central.arubanetworks.com       | :::          |
|AP NorthEast |rcs-ng-apaceast.central.arubanetworks.com    |Porta SSH 443 |
| :::         |rcs-ng-xp-apaceast.central.arubanetworks.com | :::          |
|AP SouthEast |rcs-ng-apacsouth.central.arubanetworks.com   |Porta SSH 443 |
| :::         |rcs-ng-xp-apacsouth.central.arubanetworks.com| :::          |
|UAE North    |rcs-ng-uaenorth1.central.arubanetworks.com   |Porta SSH 443 |
</table>

<table tab_label>
<caption>Outros nomes de domínio. \\ FONTE: [(:harvard:Aruba-Central-User-Guide>>direct:yes;pages:102-103)].</caption>
^Nome de domínio        ^Protocolo     ^Descrição ^
|sso.arubanetworks.com  |Porta TCP 443 |Permite que os usuários acessem suas contas no servidor interno. |
|internal.central.arubanetworks.com  |Porta TCP 443 |Permite que os usuários acessem o portal Aruba Central Internal. |
|internal2.central.arubanetworks.com | :::          | ::: |
|pool.ntp.org |Porta UDP 123 |Permite aos usuários atualizar o relógio interno e configurar fuso horário quando um dispositivo com configuração padrão de fábrica surge. \\ Por padrão, os dispositivos Aruba entram em contato com pool.ntp.org e usam o protocolo NTP para sincronizar os relógios do sistema. |
|activate.arubanetworks.com |Porta TCP 443 |Permite que os usuários configurem regras de provisionamento no Activate. |
|stun.pqm.arubanetworks.com |Porta UDP ou TCP 3478 e 3479 |Permite que os usuários descubram o endereço IP público do uplink WAN configurado nos dispositivos. |
|pqm.arubanetworks.com |Porta ICMP ou UDP 4500 |Permite que os usuários verifiquem a integridade dos uplinks WAN configurados em Branch Gateways. |
|common.cloud.hpe.com/ccssvc/ccssystem-firmware-registry |Porta TCP 80 \\ Porta TCP 443 |Permite que os usuários acessem o servidor CloudFront para localizar todas as imagens de software do tipo de dispositivo. |
|d20kce0f6gvxjn.cloudfront.net |Porta TCP 443 |Permite que os usuários acessem o servidor CloudFront enquanto o Aruba IDPS está habilitado nos gateways do Aruba Central. \\ **NOTA**: Este URL pode ser invocado apenas por gateways que tenham a segurança IDPS ativada. |
|cloud.arubanetworks.com |Porta TCP 80 |Permite que os usuários abram a página de inscrição de avaliação do Aruba Central. |
|aruba.brightcloud.com |Porta TCP 443 |Permite que dispositivos acessem o servidor Webroot Brightcloud para aplicativos, categorias de aplicativos e classificação do conteúdo do site. |
|bcap15-dualstack.brightcloud.com |Porta TCP 443 |Permite que dispositivos Aruba acessem o servidor Webroot Brightcloud para categorias de sites. |
|api-dualstack.bcti.brightcloud.com |Porta TCP 443 |Permite que dispositivos Aruba acessem a reputação de IP e serviço de geolocalização IP no servidor Webroot Brightcloud. |
|database-dualstack.brightcloud.com |Porta TCP 443 |Permite que dispositivos Aruba baixem o banco de dados de classificação de site do servidor Webroot Brightcloud. |
</table>
```

But the following PHP warnings are being thrown:

```
Warning: Undefined array key 4 in /home/robertinho/public_html/wiki/inc/Parsing/Handler/Table.php on line 252

Warning: Undefined array key "" in /home/robertinho/public_html/wiki/inc/Parsing/Handler/Table.php on line 252

Warning: Trying to access array offset on value of type null in /home/robertinho/public_html/wiki/inc/Parsing/Handler/Table.php on line 252

Warning: Undefined array key 4 in /home/robertinho/public_html/wiki/inc/Parsing/Handler/Table.php on line 253

Warning: Undefined array key "" in /home/robertinho/public_html/wiki/inc/Parsing/Handler/Table.php on line 253

Warning: Trying to access array offset on value of type null in /home/robertinho/public_html/wiki/inc/Parsing/Handler/Table.php on line 253
```

### Version of DokuWiki

2024-02-06b "Kaos"

### PHP Version

8.1

### Webserver and version of webserver

Apache 2.4 on CloudLinux

### Browser and version of browser, operating system running browser

Chrome 127 on macOS

**Comment by fiwswe** [comment]
First thing you should do is remove all of the HTML tags. They are not valid DokuWiki syntax.

Then reduce your example to a minimal reproducer. I'd suggest testing each table by itself to find the one (or more) that actually cause the warnings.

From what I saw with some quick tests the missing `|` in  the following table is definitely involved in causing similar warnings:
```
^Região  ^URL do Aruba Central ^URL para conectividade de dispositivo    ^Protocolo              ^
|US-1    |app.central.arubanetworks.com            |app1.central.arubanetworks.com |Porta TCP 443 |
|US-2    |appprod2.central.arubanetworks.com       |deviceprod2.central.arubanetworks.com | ::: |
|US West |device-uswest4.central.arubanetworks.com |device-uswest4.central.arubanetworks.com | ::: |
|EU Central |appeucentral3.central.arubanetworks.com |deviceeucentral3.central.arubanetworks.com | ::: |
|CA Central |app-ca.central.arubanetworks.com |device-ca.central.arubanetworks.com | ::: |
|CN North |app.central.arubanetworks.com |device.central.arubanetworks.com | ::: |
|AP South |app2-ap.central.arubanetworks.com app1-ap.central.arubanetworks.com | ::: |
|AP Northeast |appapaceast.central.arubanetworks.com |deviceapaceast.central.arubanetworks.com | ::: |
|AP SouthEast |appapacsouth.central.arubanetworks.com |deviceapacsouth.central.arubanetworks.com | ::: |
|UAE North |appuaenorth1.central.arubanetworks.com |device-uaenorth1-d2.central.arubanetworks.com | ::: |
```

So let's try that even more reduced:
```
|k|l|m|n|
|q|r s|t|
|x|y|z|:::|
```
This seems to trigger the same warnings. Note that the row spanning seems to influence the bug.

The lines that trigger the warnings:
https://github.com/dokuwiki/dokuwiki/blob/6de67ec6f9efe768b902ace7eb42cda8bff62725/inc/Parsing/Handler/Table.php#L252-L253

I don't know, which of the multiple array accesses in these lines are at fault?
I don't understand the parser enough to determine if the root cause might be somewhere else?

If I had to guess then the fact that the rowspan in the last line might try to access a non existing cell in the second line might be the problem?

**Comment by fiwswe** [comment]
Here is an even more minimal reproducer:
```
|q|
|x|:::|
```

**Comment by fiwswe** [comment]
A quick fix that seems to work for me might be something like:
Replace
https://github.com/dokuwiki/dokuwiki/blob/6de67ec6f9efe768b902ace7eb42cda8bff62725/inc/Parsing/Handler/Table.php#L251-L254
with
```php
                            	$x = $this->tableCalls[$cellKey[$i][$lastCell]][0] ?? '';
                                if (
                                    $x == 'tablecell_open' ||
                                    $x == 'tableheader_open'
                                ) {
```
(A better name for `$x` might make more sense. But I don't understand the code enough to choose a more semantic name.)

**Comment by fiwswe** [comment]
>First thing you should do is remove all of the HTML tags. They are not valid DokuWiki syntax.

I just noticed that you might be using the [caption Plugin](https://www.dokuwiki.org/plugin:caption)? If so please ignore my comment.

As for a better name for `$x`, how about `$lastCellCall`? Would that make sense?

Alternatively we could keep the inefficient code duplication and do something like this:
```php
                                if (
                                    ($this->tableCalls[$cellKey[$i][$lastCell]][0] ?? '') == 'tablecell_open' ||
                                    ($this->tableCalls[$cellKey[$i][$lastCell]][0] ?? '') == 'tableheader_open'
                                ) {
```

**Comment by eduardomozart** [comment]
Yes, I use the Caption plug-in. 

> A quick fix that seems to work for me might be something like: Replace
> 
> https://github.com/dokuwiki/dokuwiki/blob/6de67ec6f9efe768b902ace7eb42cda8bff62725/inc/Parsing/Handler/Table.php#L251-L254
> 
> 
> with
> ```
>                             	$x = $this->tableCalls[$cellKey[$i][$lastCell]][0] ?? '';
>                                 if (
>                                     $x == 'tablecell_open' ||
>                                     $x == 'tableheader_open'
>                                 ) {
> ```
> 
> (A better name for `$x` might make more sense. But I don't understand the code enough to choose a more semantic name.)

I believe this code is easier to read.

**Comment by fiwswe** [comment]
On "Mort" I am still getting these warnings:
```
E_WARNING: Undefined array key 2
/dokuwiki-test4/inc/Parsing/Handler/Table.php(247)
#0 /dokuwiki-test4/inc/Parsing/Handler/Table.php(247): dokuwiki\ErrorHandler::errorHandler()
#1 /dokuwiki-test4/inc/Parsing/Handler/Table.php(63): dokuwiki\Parsing\Handler\Table->finalizeTable()
#2 /dokuwiki-test4/inc/Parsing/Handler/Table.php(41): dokuwiki\Parsing\Handler\Table->tableEnd()
#3 /dokuwiki-test4/inc/Parsing/ParserMode/Table.php(72): dokuwiki\Parsing\Handler\Table->process()
#4 /dokuwiki-test4/inc/Parsing/Handler.php(152): dokuwiki\Parsing\ParserMode\Table->handle()
#5 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(344): dokuwiki\Parsing\Handler->handleToken()
#6 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(260): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
#7 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(209): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
#8 /dokuwiki-test4/inc/Parsing/Parser.php(147): dokuwiki\Parsing\Lexer\Lexer->parse()
#9 /dokuwiki-test4/inc/parserutils.php(252): dokuwiki\Parsing\Parser->parse()
#10 /dokuwiki-test4/inc/parserutils.php(206): p_get_instructions()
#11 /dokuwiki-test4/inc/parserutils.php(538): p_cached_instructions()
#12 /dokuwiki-test4/inc/parserutils.php(317): p_render_metadata()
#13 /dokuwiki-test4/inc/common.php(268): p_get_metadata()
#14 /dokuwiki-test4/doku.php(101): pageinfo()
#15 {main}

E_WARNING: Undefined array key ""
/dokuwiki-test4/inc/Parsing/Handler/Table.php(247)
#0 /dokuwiki-test4/inc/Parsing/Handler/Table.php(247): dokuwiki\ErrorHandler::errorHandler()
#1 /dokuwiki-test4/inc/Parsing/Handler/Table.php(63): dokuwiki\Parsing\Handler\Table->finalizeTable()
#2 /dokuwiki-test4/inc/Parsing/Handler/Table.php(41): dokuwiki\Parsing\Handler\Table->tableEnd()
#3 /dokuwiki-test4/inc/Parsing/ParserMode/Table.php(72): dokuwiki\Parsing\Handler\Table->process()
#4 /dokuwiki-test4/inc/Parsing/Handler.php(152): dokuwiki\Parsing\ParserMode\Table->handle()
#5 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(344): dokuwiki\Parsing\Handler->handleToken()
#6 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(260): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
#7 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(209): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
#8 /dokuwiki-test4/inc/Parsing/Parser.php(147): dokuwiki\Parsing\Lexer\Lexer->parse()
#9 /dokuwiki-test4/inc/parserutils.php(252): dokuwiki\Parsing\Parser->parse()
#10 /dokuwiki-test4/inc/parserutils.php(206): p_get_instructions()
#11 /dokuwiki-test4/inc/parserutils.php(538): p_cached_instructions()
#12 /dokuwiki-test4/inc/parserutils.php(317): p_render_metadata()
#13 /dokuwiki-test4/inc/common.php(268): p_get_metadata()
#14 /dokuwiki-test4/doku.php(101): pageinfo()
#15 {main}

E_WARNING: Trying to access array offset on null
/dokuwiki-test4/inc/Parsing/Handler/Table.php(247)
#0 /dokuwiki-test4/inc/Parsing/Handler/Table.php(247): dokuwiki\ErrorHandler::errorHandler()
#1 /dokuwiki-test4/inc/Parsing/Handler/Table.php(63): dokuwiki\Parsing\Handler\Table->finalizeTable()
#2 /dokuwiki-test4/inc/Parsing/Handler/Table.php(41): dokuwiki\Parsing\Handler\Table->tableEnd()
#3 /dokuwiki-test4/inc/Parsing/ParserMode/Table.php(72): dokuwiki\Parsing\Handler\Table->process()
#4 /dokuwiki-test4/inc/Parsing/Handler.php(152): dokuwiki\Parsing\ParserMode\Table->handle()
#5 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(344): dokuwiki\Parsing\Handler->handleToken()
#6 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(260): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
#7 /dokuwiki-test4/inc/Parsing/Lexer/Lexer.php(209): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
#8 /dokuwiki-test4/inc/Parsing/Parser.php(147): dokuwiki\Parsing\Lexer\Lexer->parse()
#9 /dokuwiki-test4/inc/parserutils.php(252): dokuwiki\Parsing\Parser->parse()
#10 /dokuwiki-test4/inc/parserutils.php(206): p_get_instructions()
#11 /dokuwiki-test4/inc/parserutils.php(538): p_cached_instructions()
#12 /dokuwiki-test4/inc/parserutils.php(317): p_render_metadata()
#13 /dokuwiki-test4/inc/common.php(268): p_get_metadata()
#14 /dokuwiki-test4/doku.php(101): pageinfo()
#15 {main}
```

The table looks like this:
```
|q|
|x|:::|
```

Release 2026-07-14 "Mort"
sprintdoc dw
PHP 8.5.8 fpm-fcgi
OpenBSD 7.9
