### ISSUE TITLE
AUTHAD errors in check and debug

### ISSUE THREAD

**Issue by Geabulek** [dokuwiki/dokuwiki#4325]
### The problem

'm setting up AUTHAD authentification and it looks like dokuwiki does not get the groups from the AD. When looking for data in order to troubleshoot, I've met the 2 following bugs:

in **index?do=debug**, page ends with 
```Auth backend capabilities:
TypeError: Cannot access offset of type string on string
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the authad plugin.
More info has been written to the DokuWiki error `log.`
```
cf logs below at timestamp 2024-10-03 14:16:13

when I call index?do=check, i get 
```
TypeError: implode(): Argument #1 ($array) must be of type array, string given
An unforeseen error has occured. This is most likely a bug somewhere.

More info has been written to the DokuWiki error log.
```
cf logs below at timestamp 2024-10-03 14:19:08

NB : My issue seems close to #4004

### Version of DokuWiki

2024-02-06b "Kaos"

### PHP Version

8.2.20

### Webserver and version of webserver

Apache/2.4.62 (Debian)

### Browser and version of browser, operating system running browser

Chrome 129 on Windows 10

### Relevant logs and/or error messages

```text
2024-10-03 14:16:13	/srv/www/public/inc/auth.php(516)	E_WARNING: Undefined array key "samesitecookie"
  #0 /srv/www/public/inc/auth.php(516): dokuwiki\ErrorHandler::errorHandler()
  #1 /srv/www/public/inc/auth.php(329): auth_logoff()
  #2 /srv/www/public/inc/auth.php(232): auth_login()
  #3 [internal function]: auth_login_wrapper()
  #4 /srv/www/public/inc/Extension/Event.php(134): call_user_func_array()
  #5 /srv/www/public/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
  #6 /srv/www/public/inc/auth.php(114): dokuwiki\Extension\Event::createAndTrigger()
  #7 /srv/www/public/inc/init.php(238): auth_setup()
  #8 /srv/www/public/doku.php(38): require_once('...')
  #9 {main}
2024-10-03 14:16:13	/srv/www/public/lib/plugins/authad/auth.php(697)	TypeError: Cannot access offset of type string on string
  #0 /srv/www/public/lib/plugins/authad/auth.php(143): auth_plugin_authad->loadServerConfig()
  #1 /srv/www/public/inc/html.php(777): auth_plugin_authad->canDo()
  #2 /srv/www/public/doku.php(105): html_debug()
  #3 {main}

2024-10-03 14:19:08	/srv/www/public/inc/infoutils.php(286)	E_WARNING: Undefined array key "grps"
  #0 /srv/www/public/inc/infoutils.php(286): dokuwiki\ErrorHandler::errorHandler()
  #1 /srv/www/public/inc/Action/Check.php(24): check()
  #2 /srv/www/public/inc/ActionRouter.php(86): dokuwiki\Action\Check->preProcess()
  #3 /srv/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
  #4 /srv/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #5 /srv/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
  #6 /srv/www/public/doku.php(131): act_dispatch()
  #7 {main}
2024-10-03 14:19:08	/srv/www/public/inc/infoutils.php(286)	TypeError: implode(): Argument #1 ($array) must be of type array, string given
  #0 /srv/www/public/inc/infoutils.php(286): implode()
  #1 /srv/www/public/inc/Action/Check.php(24): check()
  #2 /srv/www/public/inc/ActionRouter.php(86): dokuwiki\Action\Check->preProcess()
  #3 /srv/www/public/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
  #4 /srv/www/public/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #5 /srv/www/public/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
  #6 /srv/www/public/doku.php(131): act_dispatch()
  #7 {main}
```

**Comment by splitbrain** [comment]
> 2024-10-03 14:16:13	/srv/www/public/inc/auth.php(516)	E_WARNING: Undefined array key "samesitecookie"

`$conf['samesitecookie']` is set in `conf/dokuwiki.php` if that is not set you installed/upgraded your wiki wrong.

> 2024-10-03 14:16:13	/srv/www/public/lib/plugins/authad/auth.php(697)	TypeError: Cannot access offset of type string on string

That line tries to set a config on the `$opts` array, which is initialized with `$this->conf`. In your case `$opts` is a string instead of an array.

To me it seems your configuration file is seriously messed up or something is interfering with the config loading.

Since this issue is a couple of months old, I assume the issue has already been fixed for you and I will close it soon.

If you still can reproduce the issue, attach your conf/dokuwiki.php and your (redacted) conf/local.php and conf/local.protected.php here.
