### ISSUE TITLE
extension/helper : E_WARNING Zend OPcache API is restricted by "restrict_api" configuration directive

### ISSUE THREAD

**Issue by Cyrille37** [dokuwiki/dokuwiki#4375]
### The problem

The `extension/helper` seems to try to do some `opcache` operation that is not available in the hosting environement aka "restrict_api".

The error message comes from Dokuwiki logviewer `do=admin&page=logviewer`.

### Version of DokuWiki

2024-02-06b "Kaos"

### PHP Version

8.1.29

### Additional environment information

The dokuwiki instance is running within an OVH Web offer.

### Relevant logs and/or error messages

```text
2024-12-12 14:49:49 E_WARNING: Zend OPcache API is restricted by "restrict_api" configuration directive/home/wiki/lib/plugins/extension/helper/extension.php(1094)
    #0 [internal function]: dokuwiki\ErrorHandler::errorHandler(2, 'Zend OPcache AP...', '/home/giquello/...', 1094)
    #1 /home/wiki/lib/plugins/extension/helper/extension.php(1094): opcache_reset()
    #2 /home/wiki/lib/plugins/extension/helper/extension.php(704): helper_plugin_extension_extension->installArchive('/home/giquello/...', true, 'corsharing')
    #3 /home/wiki/lib/plugins/extension/admin.php(80): helper_plugin_extension_extension->installOrUpdate()
    #4 /home/wiki/inc/Action/Admin.php(35): admin_plugin_extension->handle()
    #5 /home/wiki/inc/ActionRouter.php(86): dokuwiki\Action\Admin->preProcess()
    #6 /home/wiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction('admin')
    #7 /home/wiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
    #8 /home/wiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance(true)
    #9 /home/wiki/doku.php(131): act_dispatch()
    #10 {main}
```

**Comment by Cyrille37** [comment]
Thanks 👍
