### ISSUE TITLE
Regex parsing loop causing PHP timeout

### ISSUE THREAD

**Issue by Dob4115** [dokuwiki/dokuwiki#4376]
### The problem

I was trying to save a page and kept getting a timeout (error log below). As I was reviewing the page, I noticed I used an odd link syntax:  [[xxxxxxx|yyyyyyy] zzzzzz]]  After removing the closing bracket after yyyy, the page rendered fine. 

I'm not suggesting that Dokuwiki should render the incorrect syntax, but wondering if it could fail more gracefully?

### Version of DokuWiki

2024-02-06b "Kaos"

### PHP Version

8.0

### Webserver and version of webserver

Apache 2.4 on Synology Webstation

### Browser and version of browser, operating system running browser

Vivaldi 7.0; Windows 11

### Relevant logs and/or error messages

```text
2024-12-09 11:42:10

E_WARNING: Trying to access array offset on value of type null
/volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89)
#0 /volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/volume1/web/do...', 89)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 /volume1/web/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_structsection->render('metadata', Object(Doku_Renderer_metadata), Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/2 /volume1/web/dokuwiki/inc/parserutils.php(535): Doku_Renderer->plugin('structsection', Array, 5, '')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/3 /volume1/web/dokuwiki/inc/parserutils.php(299): p_render_metadata('sources:audio:b...', Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(34): p_get_metadata('sources:audio:b...')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/5 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 72)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 73)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 {main}

2024-12-09 11:42:10

E_WARNING: Trying to access array offset on value of type null
/volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89)
#0 /volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/volume1/web/do...', 89)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 /volume1/web/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_structsection->render('metadata', Object(Doku_Renderer_metadata), Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/2 /volume1/web/dokuwiki/inc/parserutils.php(535): Doku_Renderer->plugin('structsection', Array, 5, '')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/3 /volume1/web/dokuwiki/inc/parserutils.php(299): p_render_metadata('sources:audio:o...', Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(34): p_get_metadata('sources:audio:o...')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/5 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(72): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 72)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 {main}

2024-12-09 11:42:10

E_WARNING: Undefined array key 2
/volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/rest/pageinfo.php(73): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 73)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 {main}

2024-12-09 11:42:17

E_ERROR: Maximum execution time of 30 seconds exceeded
/volume1/web/dokuwiki/inc/Parsing/Lexer/ParallelRegex.php(103)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 {main}

2024-12-09 11:42:51

E_ERROR: Maximum execution time of 30 seconds exceeded
/volume1/web/dokuwiki/inc/Parsing/Lexer/ParallelRegex.php(103)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 {main}

2024-12-09 11:43:05

E_WARNING: Undefined array key "_data"
/volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(235)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(235): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 235)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 [internal function]: _my_metaheaders_action(Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/2 /volume1/web/dokuwiki/inc/Extension/Event.php(134): call_user_func_array('_my_metaheaders...', Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/3 /volume1/web/dokuwiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger('my_metaheaders...', true)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(215): dokuwiki\Extension\Event::createAndTrigger('TPL_METAHEADER...', Array, '_my_metaheaders...', true)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/5 /volume1/web/dokuwiki/lib/tpl/ad-hominem/main.php(27): my_metaheaders()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/6 /volume1/web/dokuwiki/inc/actions.php(30): include('/volume1/web/do...')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/7 /volume1/web/dokuwiki/doku.php(131): act_dispatch()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/pull/8 {main}

2024-12-09 11:43:05

E_WARNING: Undefined array key "_data"
/volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(240)
#0 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(240): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/volume1/web/do...', 240)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 [internal function]: _my_metaheaders_action(Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/2 /volume1/web/dokuwiki/inc/Extension/Event.php(134): call_user_func_array('_my_metaheaders...', Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/3 /volume1/web/dokuwiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger('my_metaheaders...', true)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/4 /volume1/web/dokuwiki/lib/tpl/ad-hominem/my_template.php(215): dokuwiki\Extension\Event::createAndTrigger('TPL_METAHEADER...', Array, '_my_metaheaders...', true)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/5 /volume1/web/dokuwiki/lib/tpl/ad-hominem/main.php(27): my_metaheaders()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/6 /volume1/web/dokuwiki/inc/actions.php(30): include('/volume1/web/do...')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/7 /volume1/web/dokuwiki/doku.php(131): act_dispatch()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/pull/8 {main}

2024-12-09 11:43:18

E_WARNING: Trying to access array offset on value of type null
/volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89)
#0 /volume1/web/dokuwiki/lib/plugins/structsection/syntax.php(89): dokuwiki\ErrorHandler::errorHandler(2, 'Trying to acces...', '/volume1/web/do...', 89)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 /volume1/web/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_structsection->render('metadata', Object(Doku_Renderer_metadata), Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/2 /volume1/web/dokuwiki/inc/parserutils.php(535): Doku_Renderer->plugin('structsection', Array, 5, '')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/3 /volume1/web/dokuwiki/inc/parserutils.php(299): p_render_metadata('biblestudy:devo...', Array)
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/4 /volume1/web/dokuwiki/inc/common.php(262): p_get_metadata('biblestudy:devo...')
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/5 /volume1/web/dokuwiki/doku.php(101): pageinfo()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/6 {main}

2024-12-09 11:43:50

E_ERROR: Maximum execution time of 30 seconds exceeded
/volume1/web/dokuwiki/inc/Parsing/Lexer/ParallelRegex.php(103)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
https://github.com/saschaleib/dokuwiki-template-ad-hominem/issues/1 {main}
```

**Comment by fiwswe** [comment]
In "Mort" this renders as an internal link to `id=xxxxxxx` (in the current namespace) and the displayed value is `yyyyyyy] zzzzzz`. No log entries are produced and there is no delay when rendering (i.e. no timeout).

So the issue seems to be fixed.

Please close if you agree.

Release 2026-07-14 "Mort"
sprintdoc dw
PHP 8.5.8 fpm-fcgi
OpenBSD 7.9
